version: '3.3'
services:
  database:
    image: mysql:5.7
    container_name: 'mysql'
    restart: always
    environment:
      MYSQL_DATABASE: 'db_teacherBot'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_TCP_PORT: 3307
    ports:
      - '3307:3307'
    volumes:
      - my-db:/var/lib/mysql
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
volumes:
  my-db: